# .upsun/config.yaml
applications:
  myapp:
    source:
      root: "/"

    type: "nodejs:24"

    mounts:
      "/.pnpm-store":
        source: local
        source_path: pnpm_store

    hooks:
      build: |
        npm i -g pnpm@10 && pnpm i --frozen-lockfile && pnpm run build

    web:
      commands:
        start: "pnpm start"
      locations:
        "/":
          passthru: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "myapp:http"
  "http://{default}/":
    type: redirect
    to: "https://{default}/"
